sudo: required
services: 
  - docker

before_install:
  - gem install bundler
  - docker build -t parinturakhia/docker-react -f Dockerfile.dev .

script:
  - docker run parinturakhia/docker-react npm run test -- --coverage